title: Haoran Peng
logo: /assets/img/1.jpg
theme: jekyll-theme-minimal
description: [Ph.D. Candidate<br>
Department of Electrical and Computer Engineering<br>
National Yang Ming Chiao Tung University<br>
(Previouly National Chiao Tung University)<br>


Rm. 516, MIRC Bldg, 1001 University Road<br>
Hsinchu, Taiwan 300<br>
Email: peng.ee07[@]nycu.edu.tw]
